version: '3.8'

services:

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
     - .:/app
    ports:
     - 8000:8000
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.tests
